# Generated by Django 4.2.11 on 2024-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(blank=True, default='', upload_to='gallery/%y/%m/%d/', verbose_name='Название файла')),
            ],
        ),
    ]
